### PR TITLE
[WIP] Added romanian translation

### PR DESCRIPTION
**Pull request by Chicken76**
Needs squashing and a symlink in site/kovri.i2p/_i18n/ (ro -> ro.yml)
I can't do these in GitHub's web interface.

### CODE REVIEW

**Comment by erciccione** [comment]
@rehrar can you help us here with the correct way to create a symlink to kovri-docs?

**Comment by anonimal** [comment]
@erciccione you'll have to create a skeleton directory in kovri-docs, copy over all the files from the english dir, the directory name will be `ro`. Then symlink/git-add symlinks here. Romanian translations can then be applied to kovri-docs.

**Comment by anonimal** [comment]
NOTICE: THIS PULL REQUEST HAS BEEN MOVED TO GitLab. Please reopen there if you wish to merge. See https://github.com/monero-project/kovri-site/issues/122 for details.

**Comment by erciccione** [comment]
Hi @Chicken76 i recovered this PR and opened a new one on GitLab: https://gitlab.com/kovri-project/kovri-site/merge_requests/127

Let me know if there is something else you would like to add and also if you can work on the documents of kovri-docs :)

**Pull request closed without merging**
