### PR TITLE
Translate "Instructions to edit Kovri website" to russian

### PR DESCRIPTION
**Pull request by monerorus**

### CODE REVIEW

**Comment by erciccione** [comment]
Thanks for this...but why? Right now we are focusing on the translation of the main README in `kovri`. See monero-project/kovri#906

@anonimal what are your feeling about this? i can't ask to translator to translate both the README of kovri-site and kovri. For some reason @monerorus made this on his own initiative.

**Comment by monerorus** [comment]
I did not know about multilang README. rehar told me somewhere there is discussion about it.
feel free to discard this PR, i'll recreate it to kovri-docs multilang README. ok?

**Comment by erciccione** [comment]
Why discard it? it's an extensive work there is no reason to throw it away :) , i'm just pointing out that we have no workflow for this and i don't know if anonimal want this readme translated. It can be merged for me, but it will probably be the only translation of this readme for some time.

**Comment by rehrar** [comment]
Oy, this seems to be my bad. I got a bit confused with the README of Kovri site and Monero site. Very sorry @monerorus

**Comment by monerorus** [comment]
i plan translate instructions for monero site too :)
don't worry i'll also post this translation on xmr.ru for russian community, this work will not be wasted :)
also i did it in educational purpos for myself (about jekyll in use)

**Comment by erciccione** [comment]
thanks @monerorus :) please keep me updated

**Comment by rehrar** [comment]
I mean, it doesn't do any harm. As you can see it just adds another README file. This can be fine to merge, I guess, but it's not a scaleable way to handle this type of stuff. Or we'd have many README files for many different languages. 

I guess, after having given it some thought the past few days, the best way would be to make a new folder in the root of the kovri-site repo labeled 'site_docs' where we can put all of these instructions. The actual README of the site can be simplified to:

1. The purpose of this site
2. Who runs/controls it
3. Links to the various translations of "How to edit" in the site_docs folder
4. Copyright and licensing info

Thoughts?

**Comment by anonimal** [comment]
>Thoughts?

Sounds fine to me. I'll await @erciccione.

**Comment by erciccione** [comment]
Yep, good for me. Should we merge this for now and then implement the changes rehrar suggested later on?

**Comment by Josexv1** [comment]
I vote to merge this, and add a link to the translation of the top of the original README. Then we can think about translating these kind of files.

**Comment by anonimal** [comment]
>Should we merge this for now and then implement the changes rehrar suggested later on?

Yes. Can someone open a new issue?

**Comment by monerorus** [comment]
also publish this on russian monero community site (https://xmr.ru/threads/511)

**Pull request merged**
