### PR TITLE
Update config file

### PR DESCRIPTION
**Pull request by rehrar**
Set encoding to utf-8

### CODE REVIEW

**Comment by Josexv1** [comment]
i think the jekyll use UTF-8 as default, there's no need to set an encoding.

**Comment by anonimal** [comment]
@rehrar are there any confirmed bugs/issues which require this PR for ruby 2.0.0+? If not, should we ACK or NACK this PR?

**Comment by rehrar** [comment]
It does, yes. This was in an effort to solve a issue with the build that pigeons was having and I was trying to isolate variables to pin it down. We figured it out so I'll take down the PR.

**Comment by Josexv1** [comment]
@rehar what issue?

**Comment by anonimal** [comment]
@rehrar Let's reopen this PR if it's needed.

**Pull request closed without merging**
